---
spring:
  application:
    name: lab-3-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/offline-repository

server:
  port: 8001